"""Stage 1 — Read and Normalize Intent (intent.md Section 8, Stage 1).

Pure text transformation: no Anthropic API call. Splits the input intent file's
"## " sections and re-labels them into the normalized field list from the spec,
preserving the original wording. Several normalized fields (Components, Data
Fields, Error States, Edge Cases, Accessibility/Security Expectations) have no
1:1 source section in the required input shape (intent.md Section 6) — rather
than fabricate content for them, this pulls the closest matching section
verbatim and labels its source explicitly.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path

REQUIRED_SECTIONS = (
    "Business Goal",
    "User Personas",
    "User Journey",
    "Required Screens",
    "Functional Requirements",
    "Non-Functional Requirements",
    "Design Constraints",
    "API / Data Requirements",
    "Acceptance Criteria",
    "Validation Expectations",
    "Out of Scope",
)

_NOT_SPECIFIED = "_Not explicitly specified in source intent._"
_HEADING_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)


@dataclass
class NormalizedIntent:
    feature_name: str
    content: str
    missing_sections: list = field(default_factory=list)


def _split_sections(markdown: str) -> dict:
    matches = list(_HEADING_RE.finditer(markdown))
    sections = {}
    for index, match in enumerate(matches):
        heading = match.group(1).strip()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown)
        sections[heading] = markdown[start:end].strip()
    return sections


def normalize(intent_path: Path) -> NormalizedIntent:
    text = intent_path.read_text(encoding="utf-8")
    sections = _split_sections(text)
    feature_name = intent_path.name.split(".intent.md")[0]
    missing_sections = [name for name in REQUIRED_SECTIONS if not sections.get(name)]

    def source(*names, fallback=_NOT_SPECIFIED):
        for name in names:
            if sections.get(name):
                return sections[name]
        return fallback

    lines = [
        f"# Normalized Intent — {feature_name}",
        "",
        "> Generated by Stage 1 (Read and Normalize Intent). Original intent language is",
        "> preserved verbatim below; only structure is normalized, per intent.md Section 8.",
        "",
        "## Feature Name",
        "",
        feature_name,
        "",
        "## Business Goal",
        "",
        source("Business Goal"),
        "",
        "## Target Users",
        "",
        source("User Personas"),
        "",
        "## Primary Workflow",
        "",
        source("User Journey"),
        "",
        "## Screens",
        "",
        source("Required Screens"),
        "",
        "## Components",
        "",
        '_Source: "Functional Requirements" — the input has no distinct "Components" section._',
        "",
        source("Functional Requirements"),
        "",
        "## Data Fields",
        "",
        '_Source: "API / Data Requirements"._',
        "",
        source("API / Data Requirements"),
        "",
        "## API Expectations",
        "",
        '_Source: "API / Data Requirements"._',
        "",
        source("API / Data Requirements"),
        "",
        "## Error States",
        "",
        "_Not explicitly separated in source intent; see Functional Requirements and",
        "Non-Functional Requirements for related content._",
        "",
        "## Edge Cases",
        "",
        "_Not explicitly separated in source intent; see Functional Requirements for",
        "related content._",
        "",
        "## Acceptance Criteria",
        "",
        source("Acceptance Criteria"),
        "",
        "## Accessibility Expectations",
        "",
        '_Source: "Non-Functional Requirements"._',
        "",
        source("Non-Functional Requirements"),
        "",
        "## Security Expectations",
        "",
        '_Source: "Non-Functional Requirements" / "Design Constraints"._',
        "",
        source("Non-Functional Requirements", "Design Constraints"),
        "",
        "## Open Questions",
        "",
    ]

    if missing_sections:
        lines.append("**Clarification report — required sections missing from the source intent:**")
        lines.append("")
        lines.extend(f"- `{name}`" for name in missing_sections)
    else:
        lines.append("_No missing required sections detected._")
    lines.append("")
    lines.append("## Out of Scope")
    lines.append("")
    lines.append(source("Out of Scope", fallback="_Not specified._"))

    return NormalizedIntent(
        feature_name=feature_name,
        content="\n".join(lines) + "\n",
        missing_sections=missing_sections,
    )
